### ISSUE TITLE
Are you open to a pull request from my fork?

### ISSUE THREAD

**Issue by rmusser01** [the-crypt-keeper/tldw#2]
Hi, thank you for the awesome project! I wanted to build something like this myself, and stumbled upon yours when looking for prior work/research into it.

I've gone ahead and made a few modifications, and am still working on it, but was curious if you'd be interested in me creating a pull request to your base repo? 

I'd be happy to lint any code/change things around as long as it makes sense.

**Comment by the-crypt-keeper** [comment]
@rmusser01 Absolutely open to collaborate here, your fork looks great! Open a PR whenever you're ready and I'll take a closer look.

**Comment by rmusser01** [comment]
@the-crypt-keeper Thank you again.
