### ISSUE TITLE
ERROR:root:Error loading config: 'NoneType' object is not subscriptable Failed to load configuration

### ISSUE THREAD

**Issue by henri-edh** [the-crypt-keeper/tldw#22]
### I am running a Ubuntu Linux [22.04] and I also tried on my Macbook M4 Pro but I keep on getting the same error:

$ python3 summarize.py -gui

ERROR:root:Error loading config: 'NoneType' object is not subscriptable
Failed to load configuration

**Comment by rmusser01** [comment]
Can you please run it again with the `-log DEBUG` command? 
That should print out explicitly where the error is occurring

**Comment by rmusser01** [comment]
Latest merge should fix your issue. Please update to the latest commit, and see if the error still occurs. If so, please run it with `summarize.py -gui -log DEBUG` and paste the full (if possible) output when the error occurs. (also thank you for filing the issue, its greatly appreciated)
