### ISSUE TITLE
Feature Request: Docker and Docker Compose Integration

### ISSUE THREAD

**Issue by flefevre** [the-crypt-keeper/tldw#29]
Hello, and thank you for your great work on this project!

I would like to propose adding integration with Docker and Docker Compose to make it easier for users to set up and run the project. Docker would help simplify the installation process, especially for those who may not be familiar with the technical details of the dependencies required to run the project. By providing a Docker setup, users could quickly start using the project in a containerized environment.

Request Details:

Dockerfile: A Dockerfile that defines the environment and dependencies for the project.

docker-compose.yml: A docker-compose.yml file to manage multi-container setups if needed and make the process of starting and stopping the application even easier.

Documentation: Instructions in the README file explaining how to build and run the project using Docker and Docker Compose.

This would make the project more accessible to a wider audience and reduce the chances of errors during installation.

Thanks again for your hard work! Looking forward to hearing your thoughts on this feature request.

François

**Comment by rmusser01** [comment]
Thank you for the kind words and suggestion! 
In the development repo, https://github.com/rmusser01/tldw/blob/main/Dockerfile there already is a Dockerfile setup, along with one configured for using the Nvidia Container toolkit so you can do GPU passthrough (untested). 

The pull request currently open on this repo will merge that feature along with a _lot_ of others, as soon as I do one more thing:
1. Fully implement onnx embeddings generation and validate its implementation

Code is in, just need to hook things together, modify the UI and valide it all works. Once I've done that, I'll merge the changes in.
