### ISSUE TITLE
Windows Install Instructions Seem Wrong

### ISSUE THREAD

**Issue by mweth** [the-crypt-keeper/tldw#46]
This could just be me, but I could not get the wget provided in quickstart to work.  I think this is because PowerShell does not interpret && the same way as other shells (like Bash). In PowerShell, each command must be separated by a semicolon (;), and conditional operators like && or || don't behave identically.

Here's how I modified the command to work in PowerShell:

wget https://raw.githubusercontent.com/rmusser01/tldw/main/Helper_Scripts/Installer_Scripts/Windows_Install_Update.bat -OutFile Windows_Install_Update.bat;
 wget https://raw.githubusercontent.com/rmusser01/tldw/main/Helper_Scripts/Installer_Scripts/Windows_Run_tldw.bat -OutFile Windows_Run_tldw.bat

**Comment by rmusser01** [comment]
Hey, thank you! No, definitely not you, that is a good catch. I actually the other night modified it to be a curl command, but forgot to edit the `&&` as well in the main repo.

I plan to merge my updates later tonight after I add keyword filtering to viewing DB items.

Thank you again!
